[package]
name = "mesage-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
diesel = { version = "2.0.3", features = ["postgres"] }
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"