version: '3.1'
services:
  postgres:
    image: 'postgres:14-alpine'
    # volumes:
    #   - './data/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: abdemot
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '127.0.0.1:5432:5432'